---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: path={{ item.certificate_file }}
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Enable Apache mods.
  copy:
    dest: "{{ apache_server_root }}/conf.modules.d/99-ansible-{{ item }}.conf"
    content: |
      LoadModule {{ item }}_module modules/mod_{{ item }}.so
    mode: 0644
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods
  file:
    path: "{{ apache_server_root }}/conf.modules.d/99-ansible-{{ item }}.conf"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache


- name: Find and remove all default config files
  find:
    paths: /etc/httpd/conf.d/
    file_type: file
  register: files_to_remove

- name: Remove files
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ files_to_remove.files }}"


- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ item.servername }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ apache_vhosts }}"
  notify: restart apache
  when: apache_create_vhosts | bool


- name: Add apache vhosts configuration.
  template:
    src: vhost_deny_all.conf.j2
    dest: "{{ apache_conf_path }}/denyall.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache


- name: Check if localhost cert exists (RHEL 8 and later).
  stat:
    path: /etc/pki/tls/certs/localhost.crt
  register: localhost_cert
  when: ansible_distribution_major_version | int >= 8

- name: Ensure httpd certs are installed (RHEL 8 and later).
  command: /usr/libexec/httpd-ssl-gencerts
  when:
    - ansible_distribution_major_version | int >= 8
    - not localhost_cert.stat.exists

- name: Ensure documentroot exist
  file:
    path: "{{ item.documentroot }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: "{{ apache_vhosts }}"


- name: Copy example index.html file to document roots of multiple vhosts
  template:
    src: index.html.j2
    dest: "{{ item.documentroot }}/index.html"
  loop: "{{ apache_vhosts }}"
  notify: restart apache
  when: apache_vhosts | length > 0
