leafs:
  hosts:
    leaf01:
      ansible_host: 192.0.2.100
    leaf02:
      ansible_host: 192.0.2.110

spines:
  hosts:
    spine01:
      ansible_host: 192.0.2.120
    spine02:
      ansible_host: 192.0.2.130

network:
  children:
    leafs:
    spines:

webservers:
  hosts:
    webserver01:
      ansible_host: 61.28.227.212
      ansible_user: stackops
      ansible_port: 234
    webserver02:
      ansible_host: 192.0.2.150

datacenter:
  children:
    network:
    webservers:
